language: php
php:
  - '7.2'
install:
  - composer install
script:
  - composer test
  - composer cs-check
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
notifications:
  webhooks: https://travis-tg.herokuapp.com/u/$TG_NOTIFY_USER_ID
