language: php
php:
  - '7.2'
services:
  - docker
  - memcached
install:
  - composer install
script:
  - docker-compose up
  - composer test
  - composer cs-check
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
notifications:
  webhooks: https://travis-tg.herokuapp.com/u/297186158
